Repository mah-shamim/leet-code-in-php, pull requests merged in 2024-08, with the labels that each got.

#184 #182, #183 leetcode problems 002678-number-of-senior-citizens submiss…
  algorithms/002678-number-of-senior-citizens/README.md
  algorithms/002678-number-of-senior-citizens/solution.php
Labels: question, easy

#185 Develop
  algorithms/002678-number-of-senior-citizens/README.md
  algorithms/002678-number-of-senior-citizens/solution.php
Labels: question, easy

#223 000058 length of last word
  algorithms/000058-length-of-last-word/README.md
  algorithms/000058-length-of-last-word/solution.php
Labels: question, easy

#224 Develop
  algorithms/000058-length-of-last-word/README.md
  algorithms/000058-length-of-last-word/solution.php
Labels: easy

#227 002134 minimum swaps to group all 1s together ii
  algorithms/002134-minimum-swaps-to-group-all-1s-together-ii/README.md
  algorithms/002134-minimum-swaps-to-group-all-1s-together-ii/solution.php
Labels: question, medium

#228 Develop
  algorithms/002134-minimum-swaps-to-group-all-1s-together-ii/README.md
  algorithms/002134-minimum-swaps-to-group-all-1s-together-ii/solution.php
Labels: question, medium

#231 #229, #230 leetcode problems 001460-make-two-arrays-equal-by-reversin…
  algorithms/001460-make-two-arrays-equal-by-reversing-subarrays/README.md
  algorithms/001460-make-two-arrays-equal-by-reversing-subarrays/solution.php
Labels: question, easy

#232 Develop
  algorithms/001460-make-two-arrays-equal-by-reversing-subarrays/README.md
  algorithms/001460-make-two-arrays-equal-by-reversing-subarrays/solution.php
Labels: question, easy

#235 #233, #234 leetcode problems 001508-range-sum-of-sorted-subarray-sums…
  algorithms/001508-range-sum-of-sorted-subarray-sums/README.md
  algorithms/001508-range-sum-of-sorted-subarray-sums/solution.php
Labels: question, medium

#236 Develop
  algorithms/001508-range-sum-of-sorted-subarray-sums/README.md
  algorithms/001508-range-sum-of-sorted-subarray-sums/solution.php
Labels: question, medium

#239 #237, #238 leetcode problems 002053-kth-distinct-string-in-an-array s…
  algorithms/002053-kth-distinct-string-in-an-array/README.md
  algorithms/002053-kth-distinct-string-in-an-array/solution.php
Labels: question, easy

#241 #237, #238 leetcode problems 002053-kth-distinct-string-in-an-array s…
  algorithms/002053-kth-distinct-string-in-an-array/README.md
Labels: question, easy

#244 #242, #243 leetcode problems 003016-minimum-number-of-pushes-to-type-…
  algorithms/003016-minimum-number-of-pushes-to-type-word-ii/README.md
  algorithms/003016-minimum-number-of-pushes-to-type-word-ii/solution.php
Labels: question, medium

#245 Develop
  algorithms/003016-minimum-number-of-pushes-to-type-word-ii/README.md
  algorithms/003016-minimum-number-of-pushes-to-type-word-ii/solution.php
Labels: question, medium

#246 #242, #243 leetcode problems 003016-minimum-number-of-pushes-to-type-…
  algorithms/003016-minimum-number-of-pushes-to-type-word-ii/README.md
Labels: question, medium

#249 000273 integer to english words
  algorithms/000273-integer-to-english-words/README.md
  algorithms/000273-integer-to-english-words/solution.php
Labels: question, hard

#250 Develop
  algorithms/000273-integer-to-english-words/README.md
  algorithms/000273-integer-to-english-words/solution.php
Labels: question, hard

#253 #251, #252 leetcode problems 000885-spiral-matrix-iii submissions 134…
  algorithms/000885-spiral-matrix-iii/README.md
  algorithms/000885-spiral-matrix-iii/solution.php
Labels: question, medium

#254 Develop
  algorithms/000885-spiral-matrix-iii/README.md
  algorithms/000885-spiral-matrix-iii/solution.php
Labels: question, medium

#295 #293, #294 leetcode problems 000840-magic-squares-in-grid submissions…
  algorithms/000840-magic-squares-in-grid/README.md
  algorithms/000840-magic-squares-in-grid/solution.php
Labels: question, medium

#296 #51, #52 leetcode problems 000075-sort-colors submissions 1350215621
  algorithms/000075-sort-colors/README.md
  algorithms/000075-sort-colors/solution.php
Labels: question, medium

#297 Develop
  algorithms/000075-sort-colors/README.md
  algorithms/000075-sort-colors/solution.php
Labels: question, medium

#300 000959 regions cut by slashes
  README.md
  algorithms/000959-regions-cut-by-slashes/README.md
  algorithms/000959-regions-cut-by-slashes/solution.php
Labels: question, medium

#301 main to develop
  README.md
  algorithms/000959-regions-cut-by-slashes/README.md
  algorithms/000959-regions-cut-by-slashes/solution.php
Labels: question, medium

#305 001568 minimum number of days to disconnect island
  README.md
  algorithms/001568-minimum-number-of-days-to-disconnect-island/README.md
  algorithms/001568-minimum-number-of-days-to-disconnect-island/solution.php
Labels: question, hard

#306 Develop
  README.md
  algorithms/001568-minimum-number-of-days-to-disconnect-island/README.md
  algorithms/001568-minimum-number-of-days-to-disconnect-island/solution.php
Labels: question, hard

#307 #53, #54 leetcode problems 000078-subsets submissions 1352482474
  algorithms/000078-subsets/README.md
Labels: question, medium

#308 Develop
  algorithms/000078-subsets/README.md
Labels: question, medium

#311 000703 kth largest element in a stream
  algorithms/000703-kth-largest-element-in-a-stream/README.md
  algorithms/000703-kth-largest-element-in-a-stream/solution.php
Labels: question, easy

#312 Develop
  algorithms/000703-kth-largest-element-in-a-stream/README.md
  algorithms/000703-kth-largest-element-in-a-stream/solution.php
Labels: question, easy

#313 #55, #56 leetcode problems 000079-word-search 1246916510
  algorithms/000079-word-search/README.md
Labels: question, medium

#316 #314, #315 leetcode problems 000040-combination-sum-ii 1354760987
  algorithms/000040-combination-sum-ii/README.md
  algorithms/000040-combination-sum-ii/solution.php
Labels: question, medium

#317 Develop
  algorithms/000040-combination-sum-ii/README.md
  algorithms/000040-combination-sum-ii/solution.php
Labels: question, medium

#321 Develop
  README.md
  algorithms/000719-find-k-th-smallest-pair-distance/README.md
  algorithms/000719-find-k-th-smallest-pair-distance/solution.php
Labels: question, hard

#323 Develop
  algorithms/000085-maximal-rectangle/README.md
  algorithms/000085-maximal-rectangle/solution.php
  algorithms/000719-find-k-th-smallest-pair-distance/README.md
  automate_git.bat
Labels: question, hard

#326 000860 lemonade change
  algorithms/000860-lemonade-change/README.md
  algorithms/000860-lemonade-change/solution.php
Labels: question, easy

#327 Develop
  algorithms/000860-lemonade-change/README.md
  algorithms/000860-lemonade-change/solution.php
Labels: question, easy

#328 #324, #325 leetcode problems 000860-lemonade-change 1356967713
  algorithms/000860-lemonade-change/README.md
Labels: question, easy

#329 000129 sum root to leaf numbers
  algorithms/000129-sum-root-to-leaf-numbers/README.md
Labels: question, medium

#330 Develop
  algorithms/000129-sum-root-to-leaf-numbers/README.md
Labels: question, medium

#333 000624 maximum distance in arrays
  algorithms/000624-maximum-distance-in-arrays/README.md
  algorithms/000624-maximum-distance-in-arrays/solution.php
Labels: question, medium

#334 Develop
  algorithms/000129-sum-root-to-leaf-numbers/README.md
  algorithms/000624-maximum-distance-in-arrays/README.md
  algorithms/000624-maximum-distance-in-arrays/solution.php
Labels: question, medium

#337 001937 maximum number of points with cost
  algorithms/001937-maximum-number-of-points-with-cost/README.md
  algorithms/001937-maximum-number-of-points-with-cost/solution.php
Labels: question, medium

#339 000131 palindrome partitioning
  algorithms/000131-palindrome-partitioning/README.md
  algorithms/000131-palindrome-partitioning/solution.php
Labels: question, medium

#340 Develop
  algorithms/000131-palindrome-partitioning/README.md
  algorithms/000131-palindrome-partitioning/solution.php
Labels: question, medium

#345 000140 word break ii
  README.md
  algorithms/000140-word-break-ii/README.md
Labels: question, hard

#349 Develop
  README.md
  algorithms/000650-2-keys-keyboard/README.md
  algorithms/000650-2-keys-keyboard/solution.php
Labels: question, medium

#355 000165 compare version numbers
  algorithms/000165-compare-version-numbers/README.md
  algorithms/000165-compare-version-numbers/solution.php
Labels: question, medium

#356 Develop
  algorithms/000165-compare-version-numbers/README.md
  algorithms/000165-compare-version-numbers/solution.php
Labels: question, medium

#361 001140 stone game ii
  algorithms/001140-stone-game-ii/README.md
  algorithms/001140-stone-game-ii/solution.php
Labels: question, medium

#362 Develop
  algorithms/001140-stone-game-ii/README.md
  algorithms/001140-stone-game-ii/solution.php
Labels: question, medium

#363 000200 number of islands
  algorithms/000200-number-of-islands/README.md
  automate_git.bat
Labels: question, medium

#364 Develop
  algorithms/000200-number-of-islands/README.md
  automate_git.bat
Labels: question, medium

#368 000664 strange printer
  algorithms/000664-strange-printer/README.md
  algorithms/000664-strange-printer/solution.php
Labels: question, hard

#369 000664 strange printer
  algorithms/000664-strange-printer/README.md
  algorithms/000664-strange-printer/solution.php
Labels: question, hard

#370 Develop
  algorithms/000664-strange-printer/README.md
Labels: question, hard

#373 000205 isomorphic strings
  algorithms/000205-isomorphic-strings/README.md
Labels: question, easy

#374 Develop
  algorithms/000205-isomorphic-strings/README.md
Labels: question, easy

#378 000476 number complement
  algorithms/000476-number-complement/README.md
  algorithms/000476-number-complement/solution.php
Labels: question, easy

#379 Develop
  algorithms/000476-number-complement/README.md
  algorithms/000476-number-complement/solution.php
  algorithms/000664-strange-printer/README.md
Labels: question, easy

#380 000237 delete node in a linked list
  algorithms/000237-delete-node-in-a-linked-list/README.md
  algorithms/000237-delete-node-in-a-linked-list/solution.php
Labels: question, medium

#381 Develop
  algorithms/000237-delete-node-in-a-linked-list/README.md
  algorithms/000237-delete-node-in-a-linked-list/solution.php
Labels: question, medium

#385 000592 fraction addition and subtraction
  algorithms/000592-fraction-addition-and-subtraction/README.md
  algorithms/000592-fraction-addition-and-subtraction/solution.php
Labels: question, medium

#386 Develop
  algorithms/000592-fraction-addition-and-subtraction/README.md
  algorithms/000592-fraction-addition-and-subtraction/solution.php
Labels: question, medium

#387 000260 single number iii
  algorithms/000260-single-number-iii/README.md
  algorithms/000260-single-number-iii/solution.php
Labels: question, medium

#388 Develop
  algorithms/000260-single-number-iii/README.md
  algorithms/000260-single-number-iii/solution.php
Labels: question, medium

#395 000564 find the closest palindrome
  algorithms/000564-find-the-closest-palindrome/README.md
  algorithms/000564-find-the-closest-palindrome/solution.php
Labels: question, hard

#396 Develop
  algorithms/000564-find-the-closest-palindrome/README.md
  algorithms/000564-find-the-closest-palindrome/solution.php
Labels: question, hard

#397 000310 minimum height trees
  algorithms/000310-minimum-height-trees/README.md
  algorithms/000310-minimum-height-trees/solution.php
Labels: question, medium

#398 Develop
  algorithms/000310-minimum-height-trees/README.md
  algorithms/000310-minimum-height-trees/solution.php
Labels: question, medium

#402 000145 binary tree postorder traversal
  algorithms/000145-binary-tree-postorder-traversal/README.md
  algorithms/000145-binary-tree-postorder-traversal/solution.php
Labels: question, easy

#403 Develop
  algorithms/000145-binary-tree-postorder-traversal/README.md
  algorithms/000145-binary-tree-postorder-traversal/solution.php
Labels: question, easy

#404 000330 patching array
  algorithms/000330-patching-array/README.md
  algorithms/000330-patching-array/solution.php
Labels: question, hard

#405 Develop
  algorithms/000330-patching-array/README.md
  algorithms/000330-patching-array/solution.php
Labels: question, hard

#409 000590 n ary tree postorder traversal
  algorithms/000590-n-ary-tree-postorder-traversal/README.md
  algorithms/000590-n-ary-tree-postorder-traversal/solution.php
Labels: question, easy

#410 000590 n ary tree postorder traversal
  algorithms/000590-n-ary-tree-postorder-traversal/README.md
  algorithms/000590-n-ary-tree-postorder-traversal/solution.php
Labels: question, easy

#412 000344 reverse string
  algorithms/000344-reverse-string/README.md
  algorithms/000344-reverse-string/solution.php
Labels: question, easy

#417 001514 path with maximum probability
  algorithms/001514-path-with-maximum-probability/README.md
  algorithms/001514-path-with-maximum-probability/solution.php
Labels: question, medium

#418 Develop
  algorithms/001514-path-with-maximum-probability/README.md
  algorithms/001514-path-with-maximum-probability/solution.php
Labels: question, medium

#419 000350 intersection of two arrays ii
  algorithms/000350-intersection-of-two-arrays-ii/README.md
Labels: question, easy

#420 Develop
  algorithms/000350-intersection-of-two-arrays-ii/README.md
Labels: question, easy

#424 001905 count sub islands
  algorithms/001905-count-sub-islands/README.md
  algorithms/001905-count-sub-islands/solution.php
Labels: question, medium

#425 Develop
  algorithms/001905-count-sub-islands/README.md
  algorithms/001905-count-sub-islands/solution.php
Labels: question, medium

#426 000402 remove k digits
  algorithms/000402-remove-k-digits/README.md
  algorithms/000402-remove-k-digits/solution.php
  changes-2020-01-14.txt
Labels: question, medium

#431 000947 most stones removed with same row or column
  algorithms/000947-most-stones-removed-with-same-row-or-column/README.md
  algorithms/000947-most-stones-removed-with-same-row-or-column/solution.php
Labels: question, medium

#432 Develop
  algorithms/000947-most-stones-removed-with-same-row-or-column/README.md
  algorithms/000947-most-stones-removed-with-same-row-or-column/solution.php
Labels: question, medium

#433 000404 sum of left leaves
  algorithms/000404-sum-of-left-leaves/README.md
Labels: question, easy

#434 Develop
  algorithms/000404-sum-of-left-leaves/README.md
Labels: question, easy

#438 002699 modify graph edge weights
  algorithms/002699-modify-graph-edge-weights/README.md
  algorithms/002699-modify-graph-edge-weights/solution.php
Labels: question, hard

#439 Develop
  algorithms/000404-sum-of-left-leaves/README.md
  algorithms/002699-modify-graph-edge-weights/README.md
  algorithms/002699-modify-graph-edge-weights/solution.php
Labels: question, hard

#441 Develop
  algorithms/000409-longest-palindrome/README.md
  algorithms/000409-longest-palindrome/solution.php
Labels: question, hard

#445 001595 minimum cost to connect two groups of points
  algorithms/001595-minimum-cost-to-connect-two-groups-of-points/README.md
  algorithms/001595-minimum-cost-to-connect-two-groups-of-points/solution.php
Labels: question, hard

#446 Develop
  algorithms/001595-minimum-cost-to-connect-two-groups-of-points/README.md
  algorithms/001595-minimum-cost-to-connect-two-groups-of-points/solution.php
Labels: question, hard

#448 Develop
  algorithms/000445-add-two-numbers-ii/README.md
  algorithms/000445-add-two-numbers-ii/solution.php
Labels: question, medium
