Repository mah-shamim/leet-code-in-php, pull requests merged in 2024-09, with the labels that each got.

#452 002022 convert 1d array into 2d array
  algorithms/002022-convert-1d-array-into-2d-array/README.md
  algorithms/002022-convert-1d-array-into-2d-array/solution.php
Labels: question, easy

#453 develop...main
  algorithms/002022-convert-1d-array-into-2d-array/README.md
  algorithms/002022-convert-1d-array-into-2d-array/solution.php
Labels: question, easy

#454 #450, #451 leetcode problems 002022-convert-1d-array-into-2d-array su…
  algorithms/002022-convert-1d-array-into-2d-array/README.md
Labels: question, easy

#455 Develop
  algorithms/002022-convert-1d-array-into-2d-array/README.md
Labels: question, easy

#456 000463 island perimeter
  algorithms/000463-island-perimeter/README.md
  algorithms/000463-island-perimeter/solution.php
Labels: question, easy

#457 Develop
  algorithms/000463-island-perimeter/README.md
  algorithms/000463-island-perimeter/solution.php
Labels: question, easy

#461 001894 find the student that will replace the chalk
  algorithms/001894-find-the-student-that-will-replace-the-chalk/README.md
  algorithms/001894-find-the-student-that-will-replace-the-chalk/solution.php
Labels: question, medium

#462 Develop
  algorithms/001894-find-the-student-that-will-replace-the-chalk/README.md
  algorithms/001894-find-the-student-that-will-replace-the-chalk/solution.php
Labels: question, medium

#463 000502 ipo
  algorithms/000502-ipo/README.md
  algorithms/000502-ipo/solution.php
Labels: question, hard

#464 Develop
  algorithms/000502-ipo/README.md
  algorithms/000502-ipo/solution.php
Labels: question, hard

#471 001945 sum of digits of string after convert
  algorithms/001945-sum-of-digits-of-string-after-convert/README.md
  algorithms/001945-sum-of-digits-of-string-after-convert/solution.php
Labels: question, easy

#472 Develop
  algorithms/001945-sum-of-digits-of-string-after-convert/README.md
  algorithms/001945-sum-of-digits-of-string-after-convert/solution.php
Labels: question, easy

#473 000506 relative ranks
  algorithms/000506-relative-ranks/README.md
  algorithms/000506-relative-ranks/solution.php
Labels: question, easy

#474 Develop
  algorithms/000506-relative-ranks/README.md
  algorithms/000506-relative-ranks/solution.php
Labels: question, easy

#477 000874 walking robot simulation
  algorithms/000874-walking-robot-simulation/README.md
  algorithms/000874-walking-robot-simulation/solution.php
Labels: question, medium

#478 Develop
  algorithms/000874-walking-robot-simulation/README.md
  algorithms/000874-walking-robot-simulation/solution.php
Labels: question, medium

#479 000514 freedom trail
  algorithms/000514-freedom-trail/README.md
  algorithms/000514-freedom-trail/solution.php
Labels: question, hard

#480 Develop
  algorithms/000514-freedom-trail/README.md
  algorithms/000514-freedom-trail/solution.php
Labels: question, hard

#485 002028 find missing observations
  algorithms/002028-find-missing-observations/README.md
  algorithms/002028-find-missing-observations/solution.php
Labels: question, medium

#484 002028 find missing observations
  algorithms/002028-find-missing-observations/README.md
  algorithms/002028-find-missing-observations/solution.php
Labels: question, medium

#487 000523 continuous subarray sum
  algorithms/000523-continuous-subarray-sum/README.md
  algorithms/000523-continuous-subarray-sum/solution.php
Labels: question, medium

#488 Develop
  algorithms/000523-continuous-subarray-sum/README.md
  algorithms/000523-continuous-subarray-sum/solution.php
Labels: question, medium

#491 001367 linked list in binary tree
  algorithms/001367-linked-list-in-binary-tree/README.md
  algorithms/001367-linked-list-in-binary-tree/solution.php
Labels: question, medium

#492 Develop
  algorithms/001367-linked-list-in-binary-tree/README.md
  algorithms/001367-linked-list-in-binary-tree/solution.php
Labels: question, medium

#495 #493, #494 leetcode problems 003217-delete-nodes-from-linked-list-pre…
  algorithms/003217-delete-nodes-from-linked-list-present-in-array/README.md
  algorithms/003217-delete-nodes-from-linked-list-present-in-array/solution.php
Labels: question, medium

#496 Develop
  algorithms/003217-delete-nodes-from-linked-list-present-in-array/README.md
  algorithms/003217-delete-nodes-from-linked-list-present-in-array/solution.php
Labels: question, medium

#497 000552 student attendance record ii
  algorithms/000552-student-attendance-record-ii/README.md
Labels: question, hard

#498 Develop
  algorithms/000552-student-attendance-record-ii/README.md
Labels: question, hard

#505 000725 split linked list in parts
  algorithms/000725-split-linked-list-in-parts/README.md
  algorithms/000725-split-linked-list-in-parts/solution.php
Labels: question, medium

#506 Develop
  algorithms/000725-split-linked-list-in-parts/README.md
  algorithms/000725-split-linked-list-in-parts/solution.php
Labels: question, medium

#507 000623 add one row to tree
  algorithms/000623-add-one-row-to-tree/README.md
  algorithms/000623-add-one-row-to-tree/solution.php
Labels: question, medium

#508 Develop
  algorithms/000623-add-one-row-to-tree/README.md
  algorithms/000623-add-one-row-to-tree/solution.php
Labels: question, medium

#511 002326 spiral matrix iv
  algorithms/002326-spiral-matrix-iv/README.md
  algorithms/002326-spiral-matrix-iv/solution.php
Labels: question, medium

#512 Develop
  algorithms/002326-spiral-matrix-iv/README.md
  algorithms/002326-spiral-matrix-iv/solution.php
Labels: question, medium

#513 000633 sum of square numbers
  algorithms/000633-sum-of-square-numbers/README.md
  algorithms/000633-sum-of-square-numbers/solution.php
Labels: question, medium

#514 Develop
  algorithms/000633-sum-of-square-numbers/README.md
  algorithms/000633-sum-of-square-numbers/solution.php
Labels: question, medium

#517 002807 insert greatest common divisors in linked list
  algorithms/002807-insert-greatest-common-divisors-in-linked-list/README.md
  algorithms/002807-insert-greatest-common-divisors-in-linked-list/solution.php
Labels: question, medium

#518 Develop
  algorithms/002807-insert-greatest-common-divisors-in-linked-list/README.md
  algorithms/002807-insert-greatest-common-divisors-in-linked-list/solution.php
Labels: question, medium

#519 000648 replace words
  algorithms/000648-replace-words/README.md
  algorithms/000648-replace-words/solution.php
Labels: question, medium

#520 Develop
  algorithms/000648-replace-words/README.md
  algorithms/000648-replace-words/solution.php
Labels: question, medium

#523 002220 minimum bit flips to convert number
  algorithms/002220-minimum-bit-flips-to-convert-number/README.md
  algorithms/002220-minimum-bit-flips-to-convert-number/solution.php
Labels: question, easy

#524 Develop
  algorithms/002220-minimum-bit-flips-to-convert-number/README.md
  algorithms/002220-minimum-bit-flips-to-convert-number/solution.php
Labels: question, easy

#525 000678 valid parenthesis string
  algorithms/000678-valid-parenthesis-string/README.md
  algorithms/000678-valid-parenthesis-string/solution.php
Labels: question, medium

#532 001684 count the number of consistent strings
  algorithms/001684-count-the-number-of-consistent-strings/README.md
  algorithms/001684-count-the-number-of-consistent-strings/solution.php
Labels: question, easy

#533 Develop
  algorithms/001684-count-the-number-of-consistent-strings/README.md
  algorithms/001684-count-the-number-of-consistent-strings/solution.php
Labels: question, easy

#536 001310 xor queries of a subarray
  algorithms/001310-xor-queries-of-a-subarray/README.md
  algorithms/001310-xor-queries-of-a-subarray/solution.php
Labels: question, medium

#537 Develop
  algorithms/001310-xor-queries-of-a-subarray/README.md
  algorithms/001310-xor-queries-of-a-subarray/solution.php
Labels: question, medium

#540 002419 longest subarray with maximum bitwise and
  algorithms/002419-longest-subarray-with-maximum-bitwise-and/README.md
  algorithms/002419-longest-subarray-with-maximum-bitwise-and/solution.php
Labels: question, medium

#541 Develop
  algorithms/002419-longest-subarray-with-maximum-bitwise-and/README.md
  algorithms/002419-longest-subarray-with-maximum-bitwise-and/solution.php
Labels: question, medium

#544 001371 find the longest substring containing vowels in even counts
  algorithms/001371-find-the-longest-substring-containing-vowels-in-even-counts/README.md
  algorithms/001371-find-the-longest-substring-containing-vowels-in-even-counts/solution.php
Labels: question, medium

#545 Develop
  algorithms/001371-find-the-longest-substring-containing-vowels-in-even-counts/README.md
  algorithms/001371-find-the-longest-substring-containing-vowels-in-even-counts/solution.php
Labels: question, medium

#546 000752 open the lock
  algorithms/000752-open-the-lock/README.md
  algorithms/000752-open-the-lock/solution.php
Labels: question, medium

#547 Develop
  algorithms/000752-open-the-lock/README.md
  algorithms/000752-open-the-lock/solution.php
Labels: question, medium

#550 000539 minimum time difference
  algorithms/000539-minimum-time-difference/README.md
  algorithms/000539-minimum-time-difference/solution.php
Labels: question, medium

#551 Develop
  algorithms/000539-minimum-time-difference/README.md
  algorithms/000539-minimum-time-difference/solution.php
Labels: question, medium

#552 000786 k th smallest prime fraction
  algorithms/000786-k-th-smallest-prime-fraction/README.md
  algorithms/000786-k-th-smallest-prime-fraction/solution.php
Labels: question, medium

#553 Develop
  algorithms/000786-k-th-smallest-prime-fraction/README.md
  algorithms/000786-k-th-smallest-prime-fraction/solution.php
Labels: question, medium

#563 Develop
  algorithms/000884-uncommon-words-from-two-sentences/README.md
  algorithms/000884-uncommon-words-from-two-sentences/solution.php
Labels: question, easy

#564 000826 most profit assigning work
  algorithms/000826-most-profit-assigning-work/README.md
  algorithms/000826-most-profit-assigning-work/solution.php
Labels: question, medium

#567 000179 largest number
  algorithms/000179-largest-number/README.md
  algorithms/000179-largest-number/solution.php
Labels: question, medium

#568 Develop
  algorithms/000179-largest-number/README.md
  algorithms/000179-largest-number/solution.php
Labels: question, medium

#569 000834 sum of distances in tree
  algorithms/000834-sum-of-distances-in-tree/README.md
  algorithms/000834-sum-of-distances-in-tree/solution.php
Labels: question, hard

#570 Develop
  algorithms/000834-sum-of-distances-in-tree/README.md
  algorithms/000834-sum-of-distances-in-tree/solution.php
Labels: question, hard

#573 000241 different ways to add parentheses
  algorithms/000241-different-ways-to-add-parentheses/README.md
  algorithms/000241-different-ways-to-add-parentheses/solution.php
Labels: question, medium

#574 Develop
  algorithms/000241-different-ways-to-add-parentheses/README.md
  algorithms/000241-different-ways-to-add-parentheses/solution.php
Labels: question, medium

#575 000846 hand of straights
  algorithms/000846-hand-of-straights/README.md
  algorithms/000846-hand-of-straights/solution.php
Labels: question, medium

#576 Develop
  algorithms/000846-hand-of-straights/README.md
  algorithms/000846-hand-of-straights/solution.php
Labels: question, medium

#579 000214 shortest palindrome
  algorithms/000214-shortest-palindrome/README.md
  algorithms/000214-shortest-palindrome/solution.php
Labels: question, hard

#580 Develop
  algorithms/000214-shortest-palindrome/README.md
  algorithms/000214-shortest-palindrome/solution.php
Labels: question, hard

#581 000857 minimum cost to hire k workers
  algorithms/000857-minimum-cost-to-hire-k-workers/README.md
  algorithms/000857-minimum-cost-to-hire-k-workers/solution.php
Labels: question, hard

#582 Develop
  algorithms/000857-minimum-cost-to-hire-k-workers/README.md
  algorithms/000857-minimum-cost-to-hire-k-workers/solution.php
Labels: question, hard

#585 000386 lexicographical numbers
  algorithms/000386-lexicographical-numbers/README.md
  algorithms/000386-lexicographical-numbers/solution.php
Labels: question, medium

#586 Develop
  algorithms/000386-lexicographical-numbers/README.md
  algorithms/000386-lexicographical-numbers/solution.php
Labels: question, medium

#589 000440 k th smallest in lexicographical order
  algorithms/000440-k-th-smallest-in-lexicographical-order/README.md
  algorithms/000440-k-th-smallest-in-lexicographical-order/solution.php
Labels: question, hard

#590 Develop
  algorithms/000440-k-th-smallest-in-lexicographical-order/README.md
  algorithms/000440-k-th-smallest-in-lexicographical-order/solution.php
Labels: question, hard

#591 000861 score after flipping matrix
  algorithms/000861-score-after-flipping-matrix/README.md
  algorithms/000861-score-after-flipping-matrix/solution.php
Labels: question, medium

#592 Develop
  algorithms/000861-score-after-flipping-matrix/README.md
  algorithms/000861-score-after-flipping-matrix/solution.php
Labels: question, medium

#593 000881 boats to save people
  algorithms/000881-boats-to-save-people/README.md
  algorithms/000881-boats-to-save-people/solution.php
Labels: question, medium

#594 Develop
  algorithms/000881-boats-to-save-people/README.md
  algorithms/000881-boats-to-save-people/solution.php
Labels: question, medium

#603 002707 extra characters in a string
  algorithms/002707-extra-characters-in-a-string/README.md
  algorithms/002707-extra-characters-in-a-string/solution.php
Labels: question, medium

#604 Develop
  algorithms/002707-extra-characters-in-a-string/README.md
  algorithms/002707-extra-characters-in-a-string/solution.php
Labels: question, medium

#607 003043 find the length of the longest common prefix
  algorithms/003043-find-the-length-of-the-longest-common-prefix/README.md
  algorithms/003043-find-the-length-of-the-longest-common-prefix/solution.php
Labels: question, medium

#608 Develop
  algorithms/003043-find-the-length-of-the-longest-common-prefix/README.md
  algorithms/003043-find-the-length-of-the-longest-common-prefix/solution.php
Labels: question, medium

#611 002416 sum of prefix scores of strings
  algorithms/002416-sum-of-prefix-scores-of-strings/README.md
  algorithms/002416-sum-of-prefix-scores-of-strings/solution.php
Labels: question, hard

#612 Develop
  algorithms/002416-sum-of-prefix-scores-of-strings/README.md
  algorithms/002416-sum-of-prefix-scores-of-strings/solution.php
Labels: question, hard

#615 000729 my calendar i
  algorithms/000729-my-calendar-i/README.md
  algorithms/000729-my-calendar-i/solution.php
Labels: question, medium

#616 Develop
  algorithms/000729-my-calendar-i/README.md
  algorithms/000729-my-calendar-i/solution.php
Labels: question, medium

#619 #617, #618 leetcode problems 000731-my-calendar-ii submissions 140400…
  algorithms/000731-my-calendar-ii/README.md
  algorithms/000731-my-calendar-ii/solution.php
Labels: question, medium, hacktoberfest-accepted

#620 Develop
  algorithms/000731-my-calendar-ii/README.md
  algorithms/000731-my-calendar-ii/solution.php
Labels: question, medium, hacktoberfest-accepted

#625 000641 design circular deque
  algorithms/000641-design-circular-deque/README.md
  algorithms/000641-design-circular-deque/solution.php
Labels: question, medium, hacktoberfest-accepted

#626 Develop
  algorithms/000641-design-circular-deque/README.md
  algorithms/000641-design-circular-deque/solution.php
Labels: question, medium, hacktoberfest-accepted

#629 000432 all oone data structure
  algorithms/000432-all-oone-data-structure/README.md
  algorithms/000432-all-oone-data-structure/solution.php
Labels: question, hard, hacktoberfest-accepted

#630 Develop
  algorithms/000432-all-oone-data-structure/README.md
  algorithms/000432-all-oone-data-structure/solution.php
Labels: question, hard, hacktoberfest-accepted

#633 001381 design a stack with increment operation
  algorithms/001381-design-a-stack-with-increment-operation/README.md
  algorithms/001381-design-a-stack-with-increment-operation/solution.php
Labels: question, medium, hacktoberfest-accepted

#634 Develop
  algorithms/001381-design-a-stack-with-increment-operation/README.md
  algorithms/001381-design-a-stack-with-increment-operation/solution.php
Labels: question, medium, hacktoberfest-accepted
